td3:
  state_dim: 24
  action_dim: 18
  gamma: 0.99
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2
  batch_size: 256
  buffer_size: 1000000
  device: cpu
  exploration_noise: true
  exploration_noise_std: 0.1

  actor:
    hidden_layers: [256, 256]
    activation: relu
    learning_rate: 0.001
    weight_decay: 0.0
    batch_norm: false

  critic:
    hidden_layers: [256, 256]
    activation: relu
    learning_rate: 0.001
    weight_decay: 0.0001
    batch_norm: false

env:
  type: simulation
  max_episode_steps: 1000
  reward_function: default
  reward_scale: 1.0

hexapod:
  velocity_weight: 1.0
  energy_weight: 0.1
  stability_weight: 1.0
  smoothness_weight: 0.5
  use_imu: true
  use_leg_positions: true
  step_time: 0.05

training:
  max_epochs: 500
  steps_per_epoch: 5000
  evaluate_every: 5
  evaluation_episodes: 10
  save_path: models
  log_path: logs
  render: false

tidl:
  model_path: models/tidl_model
  num_eve_cores: 2
  num_dsp_cores: 2
  quantize: true
  quantization_bits: 8
  calibration_file: models/calibration.bin

opencl:
  platform_index: 0
  device_index: 0
  use_local_mem: true
  profiling: false
