# Build jobs for different components

build_driver:
  stage: build
  script:
    - ./scripts/build.sh -b driver
  artifacts:
    paths:
      - deploy/hexapod_driver.ko

build_app:
  stage: build
  script:
    - ./scripts/build.sh -b app
  artifacts:
    paths:
      - deploy/hexapod_app
      - deploy/test_mpu6050
      - deploy/test_balance
      - deploy/test_calibration
      - deploy/test_servo
      - deploy/test_movement
      - deploy/test_hcsr04

build_pytd3:
  stage: build
  script:
    - ./scripts/build.sh -b pytd3
  artifacts:
    paths:
      - deploy/pytd3/

build_utilities:
  stage: build
  script:
    - ./scripts/build.sh -t
  artifacts:
    paths:
      - deploy/install.sh
      - deploy/monitor.sh

build_digram:
  stage: build
  script:
    - ./scripts/build.sh -l
  artifacts:
    paths:
      - docs/diagrams/image/*
